// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Practicas_Oracle.Models;

#nullable disable

namespace Practicas_Oracle.Migrations
{
    [DbContext(typeof(OracleAcademiaContext))]
    [Migration("20260207093719_EstructuraFinalOracle")]
    partial class EstructuraFinalOracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("MySql:CharSet", "utf8mb4")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Practicas_Oracle.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_curso");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<int?>("Creditos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("creditos");

                    b.Property<int?>("IdProfesor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_profesor");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("titulo");

                    b.HasKey("IdCurso")
                        .HasName("PK_CURSOS");

                    b.HasIndex(new[] { "IdProfesor" }, "id_profesor");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_departamento");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Presupuesto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("presupuesto")
                        .HasDefaultValueSql("0");

                    b.HasKey("IdDepartamento")
                        .HasName("PK_DEPARTAMENTOS");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_estudiante");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstudiante")
                        .HasName("PK_ESTUDIANTES");

                    b.ToTable("estudiantes", (string)null);
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Inscripcione", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdCurso")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_curso");

                    b.Property<string>("FechaInscripcion")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("fecha_inscripcion");

                    b.Property<decimal?>("NotaFinal")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("nota_final");

                    b.HasKey("IdEstudiante", "IdCurso")
                        .HasName("PK_INSCRIPCIONES")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdCurso" }, "id_curso");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Profesore", b =>
                {
                    b.Property<int>("IdProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_profesor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesor"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_departamento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProfesor")
                        .HasName("PK_PROFESORES");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasFilter("\"email\" IS NOT NULL");

                    b.HasIndex(new[] { "IdDepartamento" }, "id_departamento");

                    b.ToTable("profesores", (string)null);
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Curso", b =>
                {
                    b.HasOne("Practicas_Oracle.Models.Profesore", "IdProfesorNavigation")
                        .WithMany("Cursos")
                        .HasForeignKey("IdProfesor")
                        .HasConstraintName("cursos_ibfk_1");

                    b.Navigation("IdProfesorNavigation");
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Inscripcione", b =>
                {
                    b.HasOne("Practicas_Oracle.Models.Curso", "IdCursoNavigation")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdCurso")
                        .IsRequired()
                        .HasConstraintName("inscripciones_ibfk_2");

                    b.HasOne("Practicas_Oracle.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdEstudiante")
                        .IsRequired()
                        .HasConstraintName("inscripciones_ibfk_1");

                    b.Navigation("IdCursoNavigation");

                    b.Navigation("IdEstudianteNavigation");
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Profesore", b =>
                {
                    b.HasOne("Practicas_Oracle.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany("Profesores")
                        .HasForeignKey("IdDepartamento")
                        .HasConstraintName("profesores_ibfk_1");

                    b.Navigation("IdDepartamentoNavigation");
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Curso", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Departamento", b =>
                {
                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Practicas_Oracle.Models.Profesore", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
